"""add extended game metadata colums

Revision ID: 4dd6c697e688
Revises: 59a9fbcd1491
Create Date: 2026-03-03 13:35:38.706414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dd6c697e688'
down_revision: Union[str, Sequence[str], None] = '59a9fbcd1491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.alter_column('developers', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_game_genres_genre_id'), table_name='game_genres')
    op.drop_index(op.f('ix_game_tags_tag_id'), table_name='game_tags')
    op.add_column('games', sa.Column('estimated_owners', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('peak_ccu', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('discount_percent', sa.SmallInteger(), nullable=True))
    op.add_column('games', sa.Column('dlc_count', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('about_the_game', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('supported_languages', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('full_audio_languages', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('reviews', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('support_url', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('support_email', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('metacritic_url', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('user_score', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('score_rank', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('achievements', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('recommendations', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('average_playtime_forever', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('average_playtime_two_weeks', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('median_playtime_forever', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('median_playtime_two_weeks', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('screenshots', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('movies', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_games_metacritic_score'), table_name='games')
    op.drop_index(op.f('ix_games_price_usd'), table_name='games')
    op.drop_index(op.f('ix_games_release_date'), table_name='games')
    op.drop_index(op.f('ix_games_search_vector'), table_name='games', postgresql_using='gin')
    op.alter_column('genres', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('publishers', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('tags', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'slug',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('publishers', 'slug',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('genres', 'slug',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('ix_games_search_vector'), 'games', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_games_release_date'), 'games', ['release_date'], unique=False)
    op.create_index(op.f('ix_games_price_usd'), 'games', ['price_usd'], unique=False)
    op.create_index(op.f('ix_games_metacritic_score'), 'games', ['metacritic_score'], unique=False)
    op.drop_column('games', 'movies')
    op.drop_column('games', 'screenshots')
    op.drop_column('games', 'median_playtime_two_weeks')
    op.drop_column('games', 'median_playtime_forever')
    op.drop_column('games', 'average_playtime_two_weeks')
    op.drop_column('games', 'average_playtime_forever')
    op.drop_column('games', 'notes')
    op.drop_column('games', 'recommendations')
    op.drop_column('games', 'achievements')
    op.drop_column('games', 'score_rank')
    op.drop_column('games', 'user_score')
    op.drop_column('games', 'metacritic_url')
    op.drop_column('games', 'support_email')
    op.drop_column('games', 'support_url')
    op.drop_column('games', 'reviews')
    op.drop_column('games', 'full_audio_languages')
    op.drop_column('games', 'supported_languages')
    op.drop_column('games', 'about_the_game')
    op.drop_column('games', 'dlc_count')
    op.drop_column('games', 'discount_percent')
    op.drop_column('games', 'peak_ccu')
    op.drop_column('games', 'estimated_owners')
    op.create_index(op.f('ix_game_tags_tag_id'), 'game_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_game_genres_genre_id'), 'game_genres', ['genre_id'], unique=False)
    op.alter_column('developers', 'slug',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.alter_column('categories', 'slug',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
